language: php

php:
  - 8.0
  - 8.1
  - 8.2
  - 8.3
  - nightly

services:
  - redis-server

sudo: false
dist: jammy

matrix:
  include:
    - php: 7.2
      dist: xenial
    - php: 7.3
      dist: bionic
    - php: 7.4
      dist: focal

before_script:
  - sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then phpenv config-add ./tests/travis/php.ini; fi"
  - composer update

script:
  - vendor/bin/phpunit
